name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "1.2.1"

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Install Poetry
      #   uses: snok/install-poetry@v1
      #   with:
      #     version: ${{ env.POETRY_VERSION }}

      # - name: Set up Python ${{ env.PYTHON_VERSION }}
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: ${{ env.PYTHON_VERSION }}
      #     cache: "poetry"

      - name: Install prerequisites
        run: |
          sudo apt install -y portaudio19-dev python3-pyaudio

      - name: Install dependencies
        run: |
          poetry install

      - name: Run checks
        run: |
          echo "Checking imports order"
          poetry run isort . --check-only
          echo "Checking black codestyle"
          poetry run black . --check
          echo "Linting code"
          poetry run flake8 . --count
